name: pyissm
channels:
  - conda-forge
dependencies:
  - automake
  - blas
  - cmake
  - fortran-compiler
  - gmt=6.0.0
  - jupyterlab
  - lapack
  - libtool
  - matplotlib
  - mpich-mpicxx
  - netcdf4
  - nose
  - numpy
  - pandas
  - petsc
  - pip
  - python=3.7
  - scipy
  - triangle
  - xarray
  - pip:
    - pygmt==0.1.0
