name: pyissm
channels:
  - conda-forge
dependencies:
  - automake
  - blas
  - cmake
  - fortran-compiler
  - gmt
  - jupyterlab
  - lapack
  - libtool
  - matplotlib
  - mpich-mpicxx
  - netcdf4
  - nose
  - numpy
  - pandas
  - petsc
  - pip
  - python=3.7
  - scipy
  - triangle
  - xarray
  - pip:
    - "--editable=git+https://github.com/GenericMappingTools/pygmt.git@392c910fdf49e7112fa4032765db2b1e87f2a24f#egg=pygmt"
